### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by mackrauss** [IrishAdo/PasswordStrength#1]
Cool idea! Please consider adding a license so people know whether they can use this plugin or not!

**Comment by IrishAdo** [comment]
Sorry thought I had closed this

**Comment by IrishAdo** [comment]
FreeTard licence.

Basically you can do anything you want with this code. This is only true open source license.
- You are free to modify this code in any way.
- You are free to use this in any open source project with out it changing any of the licenses for any other files in any way.
- You are free to learn from this code an make another product from it that with out any come back.
- You are free to use this in a commercial product without it effecting your product in anyway.
- You are free to enhance this with out having to be forced to give your changes back (please do though giving back is open to you to decide)
- You are free to do any dam thing you want.
  NO Warranty or Guarantee that the calculations are correct.
